<a href="https://colab.research.google.com/github/StephenRajva/Data-Science-Classwork/blob/main/03032026_DataScience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data={"Empid":[101,102,103],
      "Name":["Aaa","Bbb","Ccc"],
      "Designation":["Engineer","","CEO"],
      "YearsOfExp":[2,4,17],
      "Age":[29,35,47],
      "Salary":[5000,7000,250000]}

df = pd.DataFrame(data)
display(df)

   Empid Name Designation  YearsOfExp  Age  Salary
0    101  Aaa    Engineer           2   29    5000
1    102  Bbb                       4   35    7000
2    103  Ccc         CEO          17   47  250000

In [ ]:
df['Age'] = df['Age'] + 3
display(df)

   Empid Name Designation  YearsOfExp  Age  Salary
0    101  Aaa    Engineer           2   32    5000
1    102  Bbb                       4   38    7000
2    103  Ccc         CEO          17   50  250000

In [ ]:
df = df.rename(columns={'YearsOfExp': 'Exp'})
display(df)

   Empid Name Designation  Exp  Age  Salary
0    101  Aaa    Engineer    2   32    5000
1    102  Bbb                4   38    7000
2    103  Ccc         CEO   17   50  250000

In [ ]:
df['Designation'] = df['Designation'].replace('', 'Unknown')
display(df)

   Empid Name Designation  Exp  Age  Salary
0    101  Aaa    Engineer    2   32    5000
1    102  Bbb     Unknown    4   38    7000
2    103  Ccc         CEO   17   50  250000

In [ ]:
df = df[df['Salary'] <= 10000]
display(df)

   Empid Name Designation  Exp  Age  Salary
0    101  Aaa    Engineer    2   32    5000
1    102  Bbb     Unknown    4   38    7000

### Joins in Pandas (Merge)

In Pandas, a 'join' operation is primarily performed using the `pd.merge()` function. This function allows you to combine two DataFrames based on common columns or indices. It's similar to SQL JOIN operations and is crucial for bringing together related data from different sources.

There are several types of joins, each determining how rows are handled when there isn't a match in both DataFrames:

*   **Inner Join (default):** Returns only the rows where there is a match in *both* DataFrames based on the specified key(s). Non-matching rows are discarded.
*   **Left Join (Left Outer Join):** Returns all rows from the *left* DataFrame and the matching rows from the right DataFrame. If there's no match in the right DataFrame, `NaN` (or `None`) is filled for the columns from the right DataFrame.
*   **Right Join (Right Outer Join):** Returns all rows from the *right* DataFrame and the matching rows from the left DataFrame. If there's no match in the left DataFrame, `NaN` (or `None`) is filled for the columns from the left DataFrame.
*   **Outer Join (Full Outer Join):** Returns all rows when there is a match in *either* the left or the right DataFrame. Where there is no match, `NaN` is filled.

**Syntax Example:**

```python
pd.merge(left_df, right_df, on='key_column', how='inner')
```

### Difference between `merge` and `concat`

While both `pd.merge()` and `pd.concat()` are used to combine DataFrames, they serve different purposes:

| Feature           | `pd.merge()`                                   | `pd.concat()`                                  |
| :---------------- | :--------------------------------------------- | :--------------------------------------------- |
| **Primary Use**   | Combining DataFrames based on common columns (like SQL JOIN). | Stacking DataFrames vertically or horizontally. |
| **Operation Type**| **Join** (combines based on shared values in a key column or index). | **Concatenation** (stacks DataFrames along an axis). |
| **Input**         | Two DataFrames (left and right).               | A list of DataFrames.                         |
| **Key Columns**   | Requires common columns or indices to match.   | Does not necessarily require common columns; can align by index or just stack as is. |
| **Alignment**     | Aligns rows based on specified key(s).         | Aligns rows or columns by index; non-matching indices result in `NaN` if `axis=0` and `join='outer'` (default) or `axis=1` and `join='outer'`. |
| **Output**        | A single DataFrame resulting from the join.    | A single DataFrame resulting from stacking.    |
| **Examples**      | Joining customer data with order data on `customer_id`. | Appending new rows of data to an existing DataFrame (`axis=0`). Appending new columns of data (`axis=1`). |
| **Parameters**    | `on`, `left_on`, `right_on`, `left_index`, `right_index`, `how` (`inner`, `left`, `right`, `outer`), etc. | `axis` (0 for rows, 1 for columns), `join` (`inner`, `outer`), `ignore_index`, `keys`, etc. |

In [ ]:
#Student Databaseas 2 dataframes

stud1 = pd.DataFrame({'Name':['A','B','C'],
                      'Mark':[50,60,70]})
stud2 = pd.DataFrame({'Name':['D','E','F'],
                      'Mark':[80,90,100]})
display(stud1)
display(stud2)

  Name  Mark
0    A    50
1    B    60
2    C    70

  Name  Mark
0    D    80
1    E    90
2    F   100

In [ ]:
# Inner Merge: Returns only matching rows (empty in this case as no common names)
print("Inner Merge:")
display(pd.merge(stud1, stud2, on='Name', how='inner'))

# Outer Merge: Returns all rows and fills NaN for non-matching entries
print("Outer Merge:")
display(pd.merge(stud1, stud2, on='Name', how='outer'))

# Left Merge: Returns all rows from stud1 and matching from stud2, NaN for non-matches in stud2
print("Left Merge:")
display(pd.merge(stud1, stud2, on='Name', how='left'))

# Right Merge: Returns all rows from stud2 and matching from stud1, NaN for non-matches in stud1
print("Right Merge:")
display(pd.merge(stud1, stud2, on='Name', how='right'))

Inner Merge:

Empty DataFrame
Columns: [Name, Mark_x, Mark_y]
Index: []

Outer Merge:

  Name  Mark_x  Mark_y
0    A    50.0     NaN
1    B    60.0     NaN
2    C    70.0     NaN
3    D     NaN    80.0
4    E     NaN    90.0
5    F     NaN   100.0

Left Merge:

  Name  Mark_x  Mark_y
0    A      50     NaN
1    B      60     NaN
2    C      70     NaN

Right Merge:

  Name  Mark_x  Mark_y
0    D     NaN      80
1    E     NaN      90
2    F     NaN     100

In [ ]:
print("Vertical Concatenation(default):")
display(pd.concat([stud1, stud2]))

print("Horizontal Concatenation:")
display(pd.concat([stud1, stud2], axis=1))

Vertical Concatenation(default):

  Name  Mark
0    A    50
1    B    60
2    C    70
0    D    80
1    E    90
2    F   100

Horizontal Concatenation:

  Name  Mark Name  Mark
0    A    50    D    80
1    B    60    E    90
2    C    70    F   100

In [ ]:
sales_data = {
    'Product': ['A', 'B', 'A', 'C', 'B'],
    'Region': ['North', 'South', 'East', 'North', 'East'],
    'Sales': [100, 150, 200, 50, 120]
}
df_sales = pd.DataFrame(sales_data)

print("Simple Sales DataFrame:")
display(df_sales)

Simple Sales DataFrame:

  Product Region  Sales
0       A  North    100
1       B  South    150
2       A   East    200
3       C  North     50
4       B   East    120

In [ ]:
print("\n--- Pivoting the DataFrame ---")
# Pivot the DataFrame to show total sales for each Product in each Region
# Using pivot_table to handle potential multiple entries for the same product-region combination by summing sales
df_pivoted_sales = pd.pivot_table(df_sales, values='Sales', index='Product', columns='Region', aggfunc='sum', fill_value=0)

print("Pivoted DataFrame (Sales by Product and Region):")
display(df_pivoted_sales)

--- Pivoting the DataFrame ---
Pivoted DataFrame (Sales by Product and Region):

Region   East  North  South
Product
A         200    100      0
B         120      0    150
C           0     50      0

In [ ]:
print("\n--- Melting the Pivoted DataFrame ---")
# Reset the index of the pivoted DataFrame to make 'Product' a regular column
df_pivoted_reset = df_pivoted_sales.reset_index()

# Melt the DataFrame back to a long format
df_melted_sales = df_pivoted_reset.melt(id_vars=['Product'], var_name='Region', value_name='Total Sales')

print("Melted DataFrame (back to long format):")
display(df_melted_sales)