<a href="https://colab.research.google.com/github/StephenRajva/Data-Science-Classwork/blob/main/3rd_Feb_(Data_Frame).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is a DataFrame?

A `DataFrame` in pandas is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns). Think of it like a spreadsheet or a SQL table. It's the most commonly used pandas object and is ideal for storing and manipulating data.

### Accessing Data: `loc` and `iloc`

Pandas provides two primary methods to access data by label (`loc`) or by integer position (`iloc`).

*   **`loc` (label-based indexing):** This method is used for selecting data based on the *labels* of rows and columns. You can use it with a single label, a list of labels, a slice of labels, or a boolean array. It's inclusive of the end label when slicing.

*   **`iloc` (integer-location based indexing):** This method is used for selecting data based on the *integer positions* of rows and columns. It's similar to standard Python list slicing, where the start index is inclusive and the stop index is exclusive.

### Example Scenario: Employee Records DataFrame

Let's create a 7x5 DataFrame representing employee records and then demonstrate `loc`, `iloc`, and other operations.

In [ ]:
import pandas as pd

# Create a dictionary to hold our employee data
data = {
    'Employee ID': ['E001', 'E002', 'E003', 'E004', 'E005', 'E006', 'E007'],
    'Name': ['Alice Smith', 'Bob Johnson', 'Charlie Brown', 'Diana Prince', 'Eve Adams', 'Frank White', 'Grace Lee'],
    'Department': ['Sales', 'Marketing', 'Engineering', 'HR', 'Sales', 'Engineering', 'Marketing'],
    'Salary': [60000, 75000, 90000, 65000, 62000, 95000, 78000],
    'Hire Date': ['2020-01-15', '2019-03-20', '2021-06-01', '2018-11-01', '2022-02-10', '2020-07-01', '2021-09-01']
}

# Create the DataFrame
employees_df = pd.DataFrame(data)

# Convert 'Hire Date' to datetime objects for better handling
employees_df['Hire Date'] = pd.to_datetime(employees_df['Hire Date'])

print("Employee Records DataFrame (7 rows x 5 columns):")
display(employees_df)

Employee Records DataFrame (7 rows x 5 columns):

  Employee ID           Name   Department  Salary  Hire Date
0        E001    Alice Smith        Sales   60000 2020-01-15
1        E002    Bob Johnson    Marketing   75000 2019-03-20
2        E003  Charlie Brown  Engineering   90000 2021-06-01
3        E004   Diana Prince           HR   65000 2018-11-01
4        E005      Eve Adams        Sales   62000 2022-02-10
5        E006    Frank White  Engineering   95000 2020-07-01
6        E007      Grace Lee    Marketing   78000 2021-09-01

### Using `loc` (Label-based Indexing)

`loc` allows you to select rows and columns by their labels.

In [ ]:
# Select a single row by its index label (e.g., the row with index 0)
print("\nSingle row with index label 0:")
display(employees_df.loc[0])

# Select multiple rows by their index labels (e.g., rows with index 1, 3, 5)
print("\nRows with index labels 1, 3, 5:")
display(employees_df.loc[[1, 3, 5]])

# Select rows using a slice of labels (inclusive of both start and end labels)
print("\nRows from index 2 to 4 (inclusive):")
display(employees_df.loc[2:4])

# Select specific columns for all rows
print("\n'Name' and 'Department' columns for all employees:")
display(employees_df.loc[:, ['Name', 'Department']])

# Select specific rows and specific columns
print("\n'Name' and 'Salary' for rows with index labels 0, 2, 6:")
display(employees_df.loc[[0, 2, 6], ['Name', 'Salary']])

# Select rows based on a condition
print("\nEmployees in the 'Engineering' department:")
display(employees_df.loc[employees_df['Department'] == 'Engineering'])

# Select 'Name' and 'Salary' for employees with Salary > 70000
print("\nNames and Salaries for employees with Salary > 70000:")
display(employees_df.loc[employees_df['Salary'] > 70000, ['Name', 'Salary']])

Single row with index label 0:

Employee ID                   E001
Name                   Alice Smith
Department                   Sales
Salary                       60000
Hire Date      2020-01-15 00:00:00
Name: 0, dtype: object

Rows with index labels 1, 3, 5:

  Employee ID          Name   Department  Salary  Hire Date
1        E002   Bob Johnson    Marketing   75000 2019-03-20
3        E004  Diana Prince           HR   65000 2018-11-01
5        E006   Frank White  Engineering   95000 2020-07-01

Rows from index 2 to 4 (inclusive):

  Employee ID           Name   Department  Salary  Hire Date
2        E003  Charlie Brown  Engineering   90000 2021-06-01
3        E004   Diana Prince           HR   65000 2018-11-01
4        E005      Eve Adams        Sales   62000 2022-02-10

'Name' and 'Department' columns for all employees:

            Name   Department
0    Alice Smith        Sales
1    Bob Johnson    Marketing
2  Charlie Brown  Engineering
3   Diana Prince           HR
4      Eve Adams        Sales
5    Frank White  Engineering
6      Grace Lee    Marketing

'Name' and 'Salary' for rows with index labels 0, 2, 6:

            Name  Salary
0    Alice Smith   60000
2  Charlie Brown   90000
6      Grace Lee   78000

Employees in the 'Engineering' department:

  Employee ID           Name   Department  Salary  Hire Date
2        E003  Charlie Brown  Engineering   90000 2021-06-01
5        E006    Frank White  Engineering   95000 2020-07-01

Names and Salaries for employees with Salary > 70000:

            Name  Salary
1    Bob Johnson   75000
2  Charlie Brown   90000
5    Frank White   95000
6      Grace Lee   78000

### Using `iloc` (Integer-location based Indexing)

`iloc` allows you to select rows and columns by their integer positions, starting from 0.

In [ ]:
# Select a single row by its integer position (e.g., the first row)
print("\nSingle row at integer position 0:")
display(employees_df.iloc[0])

# Select multiple rows by their integer positions (e.g., rows at position 1, 3, 5)
print("\nRows at integer positions 1, 3, 5:")
display(employees_df.iloc[[1, 3, 5]])

# Select rows using an integer slice (exclusive of the end index)
print("\nRows from position 2 up to (but not including) 5:")
display(employees_df.iloc[2:5])

# Select specific columns by their integer positions for all rows
print("\nColumns at integer positions 1 and 2 ('Name' and 'Department') for all employees:")
display(employees_df.iloc[:, [1, 2]])

# Select specific rows and specific columns by integer positions
print("\nRows at positions 0, 2, 6 and columns at positions 1, 3 ('Name', 'Salary'):")
display(employees_df.iloc[[0, 2, 6], [1, 3]])

# Select the last row
print("\nLast row using negative indexing:")
display(employees_df.iloc[-1])

Single row at integer position 0:

Employee ID                   E001
Name                   Alice Smith
Department                   Sales
Salary                       60000
Hire Date      2020-01-15 00:00:00
Name: 0, dtype: object

Rows at integer positions 1, 3, 5:

  Employee ID          Name   Department  Salary  Hire Date
1        E002   Bob Johnson    Marketing   75000 2019-03-20
3        E004  Diana Prince           HR   65000 2018-11-01
5        E006   Frank White  Engineering   95000 2020-07-01

Rows from position 2 up to (but not including) 5:

  Employee ID           Name   Department  Salary  Hire Date
2        E003  Charlie Brown  Engineering   90000 2021-06-01
3        E004   Diana Prince           HR   65000 2018-11-01
4        E005      Eve Adams        Sales   62000 2022-02-10

Columns at integer positions 1 and 2 ('Name' and 'Department') for all employees:

            Name   Department
0    Alice Smith        Sales
1    Bob Johnson    Marketing
2  Charlie Brown  Engineering
3   Diana Prince           HR
4      Eve Adams        Sales
5    Frank White  Engineering
6      Grace Lee    Marketing

Rows at positions 0, 2, 6 and columns at positions 1, 3 ('Name', 'Salary'):

            Name  Salary
0    Alice Smith   60000
2  Charlie Brown   90000
6      Grace Lee   78000

Last row using negative indexing:

Employee ID                   E007
Name                     Grace Lee
Department               Marketing
Salary                       78000
Hire Date      2021-09-01 00:00:00
Name: 6, dtype: object

### Common Operations with DataFrames

DataFrames are powerful and offer many operations for data manipulation and analysis.

In [ ]:
# 1. Getting information about the DataFrame
print("\nDataFrame Info:")
employees_df.info()

# 2. Descriptive statistics for numerical columns
print("\nDescriptive Statistics for Salary:")
display(employees_df['Salary'].describe())

# 3. Checking for null values
print("\nNull values per column:")
display(employees_df.isnull().sum())

# 4. Sorting data
print("\nDataFrame sorted by Salary (descending):")
display(employees_df.sort_values(by='Salary', ascending=False).head())

# 5. Grouping data
print("\nAverage Salary by Department:")
display(employees_df.groupby('Department')['Salary'].mean())

# 6. Adding a new column (e.g., 'Years at Company')
# Assuming today's date for calculation
from datetime import datetime
today = datetime.now()
employees_df['Years at Company'] = (today - employees_df['Hire Date']).dt.days / 365.25
print("\nDataFrame with 'Years at Company' column:")
display(employees_df.head())

# 7. Filtering data based on multiple conditions
print("\nEmployees in Sales with Salary > 60000:")
display(employees_df[(employees_df['Department'] == 'Sales') & (employees_df['Salary'] > 60000)])

# 8. Updating values (e.g., giving a salary raise to Marketing department)
employees_df.loc[employees_df['Department'] == 'Marketing', 'Salary'] *= 1.05 # 5% raise
print("\nSalaries updated for Marketing department (5% raise):")
display(employees_df[employees_df['Department'] == 'Marketing'])

# 9. Dropping a column
# Let's drop 'Years at Company' for demonstration, then add it back if needed
employees_df_no_years = employees_df.drop(columns=['Years at Company'])
print("\nDataFrame after dropping 'Years at Company' column:")
display(employees_df_no_years.head())

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee ID  7 non-null      object
 1   Name         7 non-null      object
 2   Department   7 non-null      object
 3   Salary       7 non-null      int64
 4   Hire Date    7 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 412.0+ bytes

Descriptive Statistics for Salary:

count        7.000000
mean     75000.000000
std      13711.309201
min      60000.000000
25%      63500.000000
50%      75000.000000
75%      84000.000000
max      95000.000000
Name: Salary, dtype: float64

Null values per column:

Employee ID    0
Name           0
Department     0
Salary         0
Hire Date      0
dtype: int64

DataFrame sorted by Salary (descending):

  Employee ID           Name   Department  Salary  Hire Date
5        E006    Frank White  Engineering   95000 2020-07-01
2        E003  Charlie Brown  Engineering   90000 2021-06-01
6        E007      Grace Lee    Marketing   78000 2021-09-01
1        E002    Bob Johnson    Marketing   75000 2019-03-20
3        E004   Diana Prince           HR   65000 2018-11-01

Average Salary by Department:

Department
Engineering    92500.0
HR             65000.0
Marketing      76500.0
Sales          61000.0
Name: Salary, dtype: float64

DataFrame with 'Years at Company' column:

  Employee ID           Name   Department  Salary  Hire Date  Years at Company
0        E001    Alice Smith        Sales   60000 2020-01-15          6.053388
1        E002    Bob Johnson    Marketing   75000 2019-03-20          6.877481
2        E003  Charlie Brown  Engineering   90000 2021-06-01          4.676249
3        E004   Diana Prince           HR   65000 2018-11-01          7.258042
4        E005      Eve Adams        Sales   62000 2022-02-10          3.980835

Employees in Sales with Salary > 60000:

  Employee ID       Name Department  Salary  Hire Date  Years at Company
4        E005  Eve Adams      Sales   62000 2022-02-10          3.980835

Salaries updated for Marketing department (5% raise):

  Employee ID         Name Department  Salary  Hire Date  Years at Company
1        E002  Bob Johnson  Marketing   78750 2019-03-20          6.877481
6        E007    Grace Lee  Marketing   81900 2021-09-01          4.424367

DataFrame after dropping 'Years at Company' column:

  Employee ID           Name   Department  Salary  Hire Date
0        E001    Alice Smith        Sales   60000 2020-01-15
1        E002    Bob Johnson    Marketing   78750 2019-03-20
2        E003  Charlie Brown  Engineering   90000 2021-06-01
3        E004   Diana Prince           HR   65000 2018-11-01
4        E005      Eve Adams        Sales   62000 2022-02-10